name: vm
dependencies:
  - base
  - bytestring >= 0.11.0.0
  - containers
  - primitive
  - random
  - vector
ghc-options:
  - -O2
  - -Wall
#  - -Werror
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
executables:
  vm:
    main: vm.hs
  teleporter:
    main: teleporter.hs
  vault:
    main: vault.hs
